# -*- coding: utf-8 -*-
"""Day 2 Task 1 Solution

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16-xCCUYYua4moZw2xDLafu8RugmbjUhY
"""

# Day 2 Task 1

while True:
  try:
    purchases = int(input("Enter the number of books purchased this month: "))
    break
  except:
    print("You have entered an invalid number")

if (purchases == 0):
  print("Sorry. You have not earned any points this month")
elif (purchases == 1):
  print("Congratulations! You have been awarded 6 points this month")
elif (purchases == 2):
   print("Congratulations! You have been awarded 16 points this month")
elif (purchases == 3):
  print("Congratulations! You have been awarded 32 points this month")
elif (purchases >= 4):
  print("Congratulations! You have been awarded 60 points this month")
else:
  print("You have entered an invalid number")

