# -*- coding: utf-8 -*-
"""Day 1 solutions

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D2O3Dt_knPbREulVkz1g203aLKV_ABRY
"""

# Day 1 Task 1

from datetime import date
day = date.today()

#Monday - Friday = 100
#Saturday = 60
#Sunday = 80

if (day=="Saturday"):
  Fare = 60
elif (day=="Sunday"):
  Fare = 80
else:
 Fare = 100

print("Date:", day)
print("Day:", day.strftime("%A")[:3])
print("Fare:", Fare)

# Day 1 Task 2

# Per 115 sq foot = 1 gallon Paint + 8 hrs labor
# 1 hr labor = $ 20, 8 hrs labor = $ 160

wall_space = float(input("Enter wall space in square feet: "))
paint_gallon_price = float(input("Enter the price of one gallon of paint: "))

coefficient = k = wall_space / 115
labor_hours = k * 8
labor_cost = labor_hours * 20
paint_gallons = k
paint_price = k * paint_gallon_price
cost = labor_cost + paint_price

print("Paint required: ", paint_gallons, "gallons")
print("Labor hours: ", labor_hours, "hours")
print("Cost of paint: $", paint_price)
print("Cost of labor: $", labor_cost)
print("Total cost for the paint job: $", cost)

